- include_vars: variables.yml

- set_fact: slavespath={{home_dir}}/hadoop/etc/hadoop/slaves

- name: mkdir sub mr-history folders
  file: path={{home_dir}}/mr-history/{{item}} state=directory
  with_items:
    - tmp
    - done

- name: Remove slaves file
  file: path={{slavespath}} state=absent

- lineinfile: dest={{slavespath}} line="{{master_name}}" create=yes

- name: add slaves hostnames to slaves files
  lineinfile: dest={{slavespath}} line="{{ hostvars[item]['host_name'] }}"
  with_items: "{{ slaves }}"

- template: src=templates/mapred-site.j2 dest={{home_dir}}/hadoop/etc/hadoop/mapred-site.xml
