- include_vars: variables.yml

# should run all commands as sudo


- name: remove openjdk
  yum: name=java-1.7.0-openjdk-* state=absent

- name: install yum packages
  yum: name={{item}} state=installed
  with_items:
    - wget
    - curl
    - dstat
    - unzip
    - ntp
    - rpcbind
    - firewalld
    - libtirpc

- file: path=/data mode=a+rwx state=directory

- name: update /etc/selinux/config
  selinux: policy=targeted state=disabled
  ignore_errors: true

- name: setenforce 0
  command: setenforce 0
  ignore_errors: true
  
- name: edit /etc/rc.local
  blockinfile:
    dest: /etc/rc.local
    block: |
      if test -f /sys/kernel/mm/transparent_hugepage/defrag; then 
           echo never > /sys/kernel/mm/transparent_hugepage/defrag;
      fi
- name: update /etc/sysctl.conf
  lineinfile: dest=/etc/sysctl.conf line="vm.swappiness = 10" regexp="vm.swappiness = 10"

- name: run required systemctl commands
  shell: "{{item}}"
  with_items:
    - systemctl disable firewalld
    - systemctl enable rpcbind
    - systemctl enable ntpd

- name: restart server
  shell: sleep 2 && /sbin/shutdown -r now
  async: 1
  poll: 0

- name: waiting 300 secs for server to come back
  become: false
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=10 timeout=300
  
- name: start required systemctl commands
  shell: "{{item}}"
  with_items:
    - systemctl enable ntpd
    - systemctl start rpcbind